ui: mocha-bdd
server: ./test/support/server.js
browsers:
  - name: chrome
    version: 29..latest
  - name: firefox
    version: latest
    platform: Mac 10.9
  - name: safari
    version: latest
  - name: ie
    version: 10
    platform: Windows 2012
  - name: ie
    version: [6..9, latest]
  - name: iphone
    version: oldest..latest
